config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile", to: 'pages#profile'
  get "write", to: 'pages#write'
  get "explore", to: 'steps#explore'
  patch "steps/:id", to: "steps#update"

  resources :trips, only: [:show, :new, :create] do
    resources :steps, only: [:new, :create]
  end

  resources :steps, only: [:show] do
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:index, :destroy]

  resources :users, only: [:show] do
    resources :followers, only: [:create, :index, :show]
  end

  resources :followers, only: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :step

  validates :step_id, uniqueness: { scope: :user_id }
end

app/controllers/favorite_controller.rb
class FavoriteController < ApplicationController
  def index
    @favorites = Favorite.where(user: current_user)
  end

  def create
    @step = Step.find(params[:step_id])
    @favorite = Favorite.new
    @favorite.step = @step
    @favorite.user = current_user
    favorite.save
  end

  def destroy
    @step = Step.find(params[:id])
    @favorite = Favorite.where(user_id: current_user.id, step_id: @step.id)
    Favorite.destroy(@favorite)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.where(user: current_user)
  end

  def create
    @step = Step.find(params[:step_id])
    @favorite = Favorite.new
    @favorite.step = @step
    @favorite.user = current_user
    @favorite.save
    respond_to do |format|
      format.html
      format.js
    end
    # redirect_to step_path(@favorite.step)
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @step = @favorite.step
    @favorite.destroy
      respond_to do |format|
      format.html
      format.js
    end
  end
end

app/views/favorites/_likebutton.html.erb
<%= link_to step_favorites_path(step_id), method: :post, remote: true, class: "like-button" do %>
  <span class='like-icon'>
    <div class='heart-animation-1'></div>
    <div class='heart-animation-2'></div>
  </span>

<% end %>

app/views/favorites/_unlikebutton.html.erb
 <%= link_to favorite_path(@favorite.id), method: :delete, remote: true, class: "like-button liked" do %>
  <span class='like-icon'>
    <div class='heart-animation-1'></div>
    <div class='heart-animation-2'></div>
  </span>
 <% end %>

app/views/favorites/create.js.erb
console.log("coucou")
 document.querySelector(".fav-btn").innerHTML = "<%= j render 'favorites/unlikebutton', step_id: @step.id %>"
// const button = document.querySelector(".like-button");
// console.log(button)
// button.addEventListener("click", (event) => {
// (this).toggleClass('liked');
// })

app/views/favorites/destroy.html.erb
<h1>Favorite#destroy</h1>
<p>Find me in app/views/favorite/destroy.html.erb</p>

app/views/favorites/destroy.js.erb
 console.log("destroy")
  document.querySelector(".fav-btn").innerHTML = "<%= j render 'favorites/likebutton', step_id: @step.id %>"

app/views/favorites/index.html.erb
<h5 class="mt-5 mb-3">Mes favoris</h5>

<div class="explorer-cards">

  <% @favorites.each do |favorite| %>
      <%=  link_to step_path(favorite.step) do %>
        <div class="card mt-3" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path favorite.step.cover_picture_key%>');">
          <div class="card-infos">
            <div class="d-flex flex-column align-items-start justify-content-between container-card-infos">
              <span style="background: rgba(255, 255, 255, 0.8); border: 1px solid rgba(255, 255, 255, 0.8); border-top-right-radius: 5px; border-bottom-right-radius: 5px; padding: 5px 10px; color: rgba(0, 0, 0, 0.6); width: 60px;"><%= "#{(favorite.step.nb_of_days)} jours" %></span>
              <p class="position-absolute w-100"><%= favorite.step.title %></p>
            </div>
          </div>
        </div>
      <% end %>
  <% end %>

</div>