config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile", to: 'pages#profile'
  get "write", to: 'pages#write'
  get "explore", to: 'steps#explore'
  patch "steps/:id", to: "steps#update"

  resources :trips, only: [:show, :new, :create] do
    resources :steps, only: [:new, :create]
  end

  resources :steps, only: [:show] do
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:index, :destroy]

  resources :users, only: [:show] do
    resources :followers, only: [:create, :index, :show]
  end

  resources :followers, only: :destroy
end

app/views/shared/_carousel_btn.html.erb
<!-- Button trigger modal -->
<button type="button" class="text-center btn btn-light mt-4 position-absolute" style="top:-5px; right:0;" data-toggle="modal" data-target="#exampleModal">
  Visualiser le voyage
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel" style="font-size: 1.2rem;"><%= @trip.title%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

          <div class="carousel-inner">
           <% @contents.each do |content| %>
            <% content.files.each do |file|  %>
              <div class="carousel-item <%= "active" if content == @contents.first && file == content.files.first %>">
                  <h6 class="mb-3">Etape <%= content.step.id_in_its_trip %> - <%= content.step.title %></h6>
                  <%= cl_image_tag file.key, class: "img-diapo"%>
              </div>
              <% end %>
            <%end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/shared/_explore_search_form.html.erb
<%= simple_form_for :search, url: explore_path, method: "GET", html: { class: "explore-form mt-5 mb-3" }, remote: true do |f| %>
  <%= f.input :keyword, placeholder: "Votre destination", label: false, input_html: { class: "form-control" } %>
  <%= f.button :submit, "Rechercher", class: "flex-grow-1", style: "height: 38px; padding: 0px 8px; margin-left: 8px; color: white; background: #E26E2D;" %>
<% end %>

app/views/shared/_fav_button.html.erb
<% if trip.user != current_user %>
  <div class="fav-btn">
    <% if @favorite.present?%>
      <%= render "favorites/unlikebutton" %>
    <% else %>
      <%= render "favorites/likebutton", step_id: @step.id %>
    <% end %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_info_window.html.erb
<div class="text-center d-flex-column" >
<%= link_to step_path(step) do %>
  <img src="<%= cl_image_path step.cover_picture_key %>" alt="" style="width: 200px; height: 150px; border-radius: 5px;">
  <% end %>
  <div class="info-card text-center">
    <h6 class="info-card-h"><%= step.location %></h6>
    <p class="info-card-p"><%= step.title %></p>
  </div>
  <!-- <img src="https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="" style="width: 200px;"> -->
</div>

app/views/shared/_logo.html.erb
<%= link_to 'TripsMap', profile_path, class: 'logo'  %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="row">
    <div class="col-xs-12">
      <nav class="align-items-center">
        <%= link_to explore_path, class: "icone-action #{current_class?(explore_path)}" do %>
          <i class="fas fa-globe-americas icones"></i> <p class="d-none d-sm-block">Explorer</p>
        <% end %>
        <%= link_to favorites_path, class: "icone-action #{current_class?(favorites_path)}" do %>
          <i class="far fa-heart"></i> <p class="d-none d-sm-block"> Enregistrés </p>
        <% end %>
        <button class="add-button">
          <%= link_to write_path, class: "icone-action-big #{current_class?(write_path)}" do %>
            <i class="fas fa-plus-circle"></i> <p class="d-none d-sm-block">Ecrire</p>
          <% end %>
        </button>
        <div class="icone-action"> <i class="far fa-comment-alt"></i> <p class="d-none d-sm-block">Messages</p></div>
        <%= link_to profile_path, class: "icone-action #{current_class?(profile_path)}" do %>
          <i class="far fa-user"></i> <p class="d-none d-sm-block"> Profil </p>
        <% end %>
      </nav>
     </div>
  </div>
</div>

app/views/shared/_profile.html.erb
<div class="d-flex justify-content-between">
  <!-- <img class="mt-2" src="https://res.cloudinary.com/datbhgbcq/image/upload/v1593113188/TRIPSMAP/TRIPSMAP_TripsMap_kc9ki7-media_lib_thumb_daviif.png" alt=""> -->
  <div class="logo">
    TripsMap
  </div>

  <div class="follow-button">
    <% if @user == current_user %>
      <button type="button" class="btn btn-light mt-4">Editer mon compte</button>
    <% else %>
      <% if @follower %>
        <%= render "followers/unfollow_button" %>
      <% else %>
        <%= render "followers/follow_button" %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="profile-infos">
  <div class="main-infos mb-3" style="text-align: center">
    <%= cl_image_tag @user.avatar.key, class: "avatar mt-5"  %>
    <h5><%= @user.pseudo %></h5>
    <p>Aventurier chevronné, j'aime parcourir le monde pour découvrir des paysages exceptionnels que nous offre la nature.</p>
  </div>
  <div class="inline-infos-trips mb-4">
    <div class="container d-flex justify-content-around">
      <div class="text-center" style="width: 52px;"><strong><span style="font-size: 1.5rem"><%= @count_steps %></span></strong> étapes</div>
      <div class="text-center" style="width: 52px;"><strong><span style="font-size: 1.5rem"><%= @trips.count %></span></strong> pays</div>
      <div id="followers-count" class="text-center" style="width: 52px;"><%= render "followers/followers_count" %></div>
    </div>
  </div>
</div>

</div>

<div id="profile-map"
     style="width: 100%; height: 500px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

<div class="container text-center">
  <h5 class="mt-4"> Mes voyages </h5>
  <div id="profile-cards" class="row">
    <% @trips.order('starts_on DESC').each do |trip| %>
      <div class="col-12 col-md-6 col-lg-4 col-xl-4">
        <%= link_to trip_path(trip) do %>
          <div class="card mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= cl_image_path trip.cover_picture.key %>');">
            <div class="card-infos">
              <div class="d-flex flex-column align-items-start justify-content-between container-card-infos">
                <span style="background: rgba(255, 255, 255, 0.8); border: 1px solid rgba(255, 255, 255, 0.8); border-top-right-radius: 5px; border-bottom-right-radius: 5px; padding: 5px 10px; color: rgba(0, 0, 0, 0.6); width: 110px;"><%= "#{l(trip.starts_on, format: '%B %Y', locale: 'fr')}" %></span>
                <h6 style="margin: 0 auto; color: #fff;"><%= trip.steps.count %> étapes</h6>
                <p class="mb-2" style="margin: 0 auto;"><%= trip.title %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_white_space.html.erb
<div style="height: 100px;">
</div>