config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile", to: 'pages#profile'
  get "write", to: 'pages#write'
  get "explore", to: 'steps#explore'
  patch "steps/:id", to: "steps#update"

  resources :trips, only: [:show, :new, :create] do
    resources :steps, only: [:new, :create]
  end

  resources :steps, only: [:show] do
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:index, :destroy]

  resources :users, only: [:show] do
    resources :followers, only: [:create, :index, :show]
  end

  resources :followers, only: :destroy
end

app/views/pages/home.html.erb
<div class="homepage-new">
  <div class="d-flex justify-content-end">
    <%= link_to "Connexion", profile_path, class: "btn btn-grey-connexion-new" %>
    <a href="#" class="btn btn-grey-inscription-new">Inscription</a>
  </div>
  <div>
    <br>
    <h1 class="logo-big-new">TripsMap</h1>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class= "text-center">
      <h2 class="white tagline-new">Ramenez vos souvenirs de vacances à la vie</h2>
    </div>
    <br>
    <br>
    <div class= "text-center">
      <p class= "white-new">Créez et revivez vos souvenirs de vacances en quelques clics !</p>
    </div>
    <br>
    <br>
    <div class="text-center">
      <a href="/profile" class="btn btn-orange-new">Commencer</a>
    </div>
  </div>
</div>

<!-- Deuxième partie (les cards)-->

<!-- <div id="ajoutsrecents" class="carousel slide carousel-multi-item" data-ride="carousel" data-keyboard="false">

 <ol class="carousel-indicators">
  <li data-target="#multi-item-example" data-slide-to="0" class="active"></li>
  <li data-target="#multi-item-example" data-slide-to="1"></li>

  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class= "row">
      <div class="col-12 col-sm-4">
        <div class="card">
          <img class="card-img-top"
          src="https://mdbootstrap.com/img/Photos/Horizontal/City/4-col/img%20(60).jpg" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">L'Amérique du Sud en 18 jours</h4>
            <p class="card-text">.....</p>
            <a class="btn btn-primary">Button</a>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-4">
        <div class="card">
          <img class="card-img-top"
          src="https://mdbootstrap.com/img/Photos/Horizontal/City/4-col/img%20(60).jpg" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">Une semaine de rêve aux Bahamas</h4>
            <p class="card-text"> .......</p>
            <a class="btn btn-primary">Button</a>
          </div>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <div class= "row">
      <div class="col-12 col-sm-4">
        <div class="card">
          <img class="card-img-top"
          src="https://mdbootstrap.com/img/Photos/Horizontal/City/4-col/img%20(60).jpg" alt="Card image cap">
          <div class="card-body">
            <h4 class="card-title">L'Amérique du Sud en 18 jours</h4>
            <p class="card-text">......</p>
            <a class="btn btn-primary">Button</a>
          </div>
        </div>
      </div>
    </div>
   </div>
  </div>

</div> -->
<!-- position-relative" ligne 33-->

app/views/pages/profile.html.erb
<%= render 'shared/profile' %>

app/views/pages/write.html.erb
<p class = "mb-4" style="margin-top: 36px; text-align: justify; text-justify: inter-character;"> Choisissez un voyage dans lequel vous souhaitez écrire une nouvelle étape: </p>

<div class= "new-trip text-center">
   <%= link_to new_trip_path, class:"btn btn-orange-new" do %>
    <p><i class="far fa-edit mr-1"></i> Nouveau voyage</p>
   <% end %>
</div>
<!-- <div class="row mt-4"> -->
  <% @trips.order('starts_on DESC').each do |trip| %>
    <div class="mt-4 p-0 w-100">
      <%= link_to new_trip_step_path(trip), class:"card-link" do %>
        <div class="d-flex">
          <div class="photo-card" style="width: 37%;">
            <%= cl_image_tag trip.cover_picture.key %>
          </div>
          <div class="w-75 content justify-content-center pl-3 pr-2">
            <div class="pb-2" id="trip-title"><%= trip.title %>
            </div>
            <div class="" id="trip-dates">
              <%= l(trip.starts_on, format: '%e %b %Y', locale: 'fr') %> - <%= l(trip.ends_on, format: '%e %b %Y', locale: 'fr') %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<!-- </div> -->