config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile", to: 'pages#profile'
  get "write", to: 'pages#write'
  get "explore", to: 'steps#explore'
  patch "steps/:id", to: "steps#update"

  resources :trips, only: [:show, :new, :create] do
    resources :steps, only: [:new, :create]
  end

  resources :steps, only: [:show] do
    resources :favorites, only: [:create]
  end

  resources :favorites, only: [:index, :destroy]

  resources :users, only: [:show] do
    resources :followers, only: [:create, :index, :show]
  end

  resources :followers, only: :destroy
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :steps, through: :user

  validates :follower_pseudo, uniqueness: { scope: [:user_id] }
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def index
    @followers = Follower.where(user: current_user)
  end

  def create
    @user = User.find(params[:user_id])
    @follower = Follower.new
    @follower.user = @user
    @follower.follower_pseudo = current_user.pseudo
    @follower.save
    @followers = @user.followers || 0

    # redirect_to user_path(@follower.user)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @follower = Follower.find(params[:id])
    @user = @follower.user
    @follower.destroy
    @followers = @user.followers || 0

    # redirect_to user_path(@user)
    respond_to do |format|
      format.js
    end
  end
end

app/views/followers/_follow_button.html.erb
<%= link_to "S'abonner", user_followers_path(@user.id), method: :post, remote: true, class: "btn btn-light mt-4" %>

app/views/followers/_followers_count.html.erb
<!-- <strong><span style="font-size: 1.5rem"><%= @followers.count %></span></strong> abonnés -->

<button type="button" class="access-followers-button" data-toggle="modal" data-target="#exampleModalCenter">
  <strong><span style="font-size: 1.5rem;"><%= @followers.count %></span></strong> abonnés
</button>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle" style="text-align: center;">Abonnés</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% @followers.order("created_at DESC").each do |follower| %>
          <div class="d-flex justify-content-between align-items-center mb-3">
            <div class="avatar-follower">
              <%= cl_image_tag User.find_by(pseudo:follower.follower_pseudo).avatar.key, class: "avatar-follower"  %>
            </div>
            <div class="follower-infos">
              <%= follower.follower_pseudo %>
            </div>
            <div class="follow-button">
              <button class="btn btn-primary">S'abonner</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/followers/_unfollow_button.html.erb
<%= link_to "Abonné(e)",follower_path(@follower.id), method: :delete, remote: true, class: "btn btn-light mt-4" %>

app/views/followers/create.html.erb
<h1>Followers#create</h1>
<p>Find me in app/views/followers/create.html.erb</p>

app/views/followers/create.js.erb
document.getElementById("followers-count").innerHTML = "<%= j render 'followers/followers_count' %>";
document.querySelector(".follow-button").innerHTML = "<%= j render 'followers/unfollow_button' %>";

app/views/followers/destroy.html.erb
<h1>Followers#destroy</h1>
<p>Find me in app/views/followers/destroy.html.erb</p>

app/views/followers/destroy.js.erb
document.getElementById("followers-count").innerHTML = "<%= j render 'followers/followers_count' %>";
document.querySelector(".follow-button").innerHTML = "<%= j render 'followers/follow_button' %>";

app/views/followers/index.html.erb
<h1>Followers#Index</h1>
<p>Find me in app/views/followers/destroy.html.erb</p>